services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - learnings

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - learnings
  
  reverse-proxy:
    container_name: reverse-proxy
    build: ./nginx
    depends_on:
      - frontend
    ports:
      - "443:443"
    networks:
      - learnings
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  learnings:
    external: true
