# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Learnings

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    # strategy:
    #   matrix:
    #     node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
        uses: docker/setup-buildx-action@v4
      # with:
      #   node-version: ${{ matrix.node-version }}
      #   cache: 'npm'
    - run: sudo docker compose up -d
